home1/urls.py
from django.urls import path
# from django.conf.urls import url
from . import views

from django.contrib.auth.views import login, logout
from .views import HomeView


app_name = "home1"

urlpatterns = [
    path(r'index/', HomeView.as_view(), name="index"),
    path(r'', login, {'template_name': 'index.html'},name="index1"),
    # path(r'index/',views.homeview,name="index"),
    # path(r'login/', login, {'template_name': 'index.html'}, name="login"),
    ]

urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import login, logout
# from django.contrib.auth.views import logout
from django.conf import settings
from django.conf.urls.static import static


app_name = "twitter"

urlpatterns = [
    # path(r'', views.home, name='home'),
    # path(r'', views.index, name="index"),
    path(r'register/', views.register, name="register"),
    path(r'search/', views.view_profile, name="view_profile"),
    path(r'profile/', views.view_profile, name="profile"),
    path(r'profile/(^?P<pk>\d+$)', views.view_profile, name="profile_with_pk"),
    path(r'edit_profile/', views.edit_profile, name="edit_profile"),
    # path(r'edit_profile/', views.edit_profileModel, name="edit_profileModel"),
    # path(r'login/', login, {'template_name' : 'includes/login.html'}, name="login"),
    path(r'logout/', logout, {'template_name' : 'includes/logout.html'}, name="logout"),
    path(r'change_password/', views.change_password, name="change_password"),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    {% load staticfiles %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link rel="stylesheet" href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>

<body>
<header id="header">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'home1:index1' %}"><img src="{% static 'images/Twitter.png' %}" alt=""></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
      {% if user.is_authenticated %}
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home1:index' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'twitter:profile' %}">Profile</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'twitter:edit_profile' %}">Edit Profile</a>
      </li>
         <li class="nav-item">
        <a class="nav-link" href="{% url 'twitter:change_password' %}">Change Password</a>
      </li>
    </ul>
      <ul class="navbar-nav my-2 my-lg-0">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'twitter:logout' %}">Logout</a>
          </li>
                </ul>

          {% else %}



          <ul class="navbar-nav mr-auto">

              <li class="nav-item">
            <a class="nav-link" href="{% url 'home1:index1' %}">Login</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'twitter:register' %}">Register</a>
          </li>
          </ul>

        {% endif %}
 </div>
</nav>
</header>

<div id="content">
    <div class="container">
    {% block content %}
    {% endblock %}
        </div>
</div>

</body>
</html>